#!/bin/bash

service=file_chkd.service

start() {
    sudo systemctl start ${service}
}

stop() {
    sudo systemctl stop ${service}
}

status() {
    sudo echo $(systemctl is-active ${service})
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    status)
       status
       ;;
    *)
       echo "Usages: $0 {start|stop|status}"
esac

exit 0 
